{% set name = "opentelemetry-instrumentation-pyramid" %}
{% set version = "0.27b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-pyramid-{{ version }}.tar.gz
  sha256: 33ff11fa5c9af8b84884a8592a7d74e7c8f5d9105dafe2925cae88802ff223d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.27b0
    - opentelemetry-instrumentation-wsgi ==0.27b0
    - opentelemetry-semantic-conventions ==0.27b0
    - opentelemetry-util-http ==0.27b0
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test ==0.24b0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.26b1
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.27b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pyramid
  summary: OpenTelemetry Pyramid instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
