{% set name = "opentelemetry-instrumentation-pyramid" %}
{% set version = "0.30b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-pyramid-{{ version }}.tar.gz
  sha256: ff2fa3ef22e3cc7db91a8aa488c2299d1e9b3f3ee34a0781a437aa6808a8760d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.30b1
    - opentelemetry-instrumentation-wsgi ==0.30b1
    - opentelemetry-semantic-conventions ==0.30b1
    - opentelemetry-util-http ==0.30b1
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test ==0.24b0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.26b1
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.27b0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.28b0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.28b1
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.29b0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.30b0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.30b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pyramid
  summary: OpenTelemetry Pyramid instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
