{% set name = "opentelemetry-instrumentation-pyramid" %}
{% set version = "0.24b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-pyramid-{{ version }}.tar.gz
  sha256: 84dc1546c22b3616747d177716547693f20a3893028731007b329c20e882433f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.24b0
    - opentelemetry-instrumentation-wsgi ==0.24b0
    - opentelemetry-semantic-conventions ==0.24b0
    - opentelemetry-util-http ==0.24b0
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test ==0.24b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pyramid
  summary: OpenTelemetry Pyramid instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
